name: Exclude some branches of PR targets
on:
  pull_request:
    branches-ignore:
      - "previous-fork"

jobs:
  deny-job:
    name: Notify when excluded branches try to PR
    runs-on: ubuntu-latest
    steps:
      - name: Exit with error
        run: exit 1