# This is a basic workflow to help you get started with Actions

name: Exclude some branches of PR targets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches-ignore: [ "previous-fork" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify-job:
    name: Notify when actions are done.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print status
        run: echo "all job is done."
